### ISSUE TITLE
Question regarding remote-backup

### ISSUE THREAD

**Issue by gerard33** [carstenschroeder/hassio-addons#1]
I am using folder-rsync and that works great. Thanks for that addon :+1: 

Currently I am also using the remote-backup addon from mr-bjerre.
Looks like I can use your forked remote-backup which does both making a snapshot and copy that via SCP and also does the rsync of the hassio folders. Is that correct?

Because then I can switch from the 2 addons to your remote-backup addon :smiley:

**Comment by carstenschroeder** [comment]
yes, that's what it does. But I do not use SCP (only rscync), so it was never tested by me.
