### ISSUE TITLE
No snapshots anymore

### ISSUE THREAD

**Issue by yvansandoz** [carstenschroeder/hassio-addons#12]
The backup process starts every night triggered by an automation, saving the "config" files to my NAS with rsync, but I dot not see the daily snapshot in HA.

Any special configuration needed?

**Comment by carstenschroeder** [comment]
Which Addon do you use? Only remote-backup does a snapshot.

**Comment by yvansandoz** [comment]
I do have remote-backup 4.2.7 running and I did initaly saw snapshots created by remote-backup in the Supervisor named "Automated Backup", but it stopped and I do not have snapshots created anymore, backup config files only.

**Comment by yvansandoz** [comment]
Here some additional information: The snapshot does work, it saves the file on the NAS and I can retrieve it. I have been unsettled by the fact that the snapshot is not automatically lister in HA/Supervisor/Snapshots under "Available Snapshots".
