### ISSUE TITLE
Share folder not synced (just the config folder)

### ISSUE THREAD

**Issue by reiniertc** [carstenschroeder/hassio-addons#15]
Somehow when I perform an RSYNC from home assistant with this integration, the /share folder is not synced. 
There is no mention of the /share in the logs either. 
IS this a bug? or something I have to configure somehow?

**Comment by reiniertc** [comment]
I performed some extra tests, that lead me to the conclusion that only the "config" folder is synced. 
I do see a lot of errors towards the end of the log, like this one:
`rsync: chgrp "/config/www/community/bootstrap-grid-card/.bootstrap-grid-card.js.gz.9kKdgA" (in backup-home_assistant) failed: Operation not permitted (1)`

all errors occur trying the same command withe the serveral subfolders of "/config/www/community".
after the errors, it ends with
`sent 741,967,250 bytes  received 1,413,949 bytes  36,262,497.51 bytes/sec
total size is 741,285,114  speedup is 1.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
[cmd] /run.sh exited 23
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by carstenschroeder** [comment]
For me it works for all folders. There might be something with the files and folders under your www folder. Something regarding File Permissions, I guess.

**Comment by reiniertc** [comment]
those permissions seem normal to me. 
But thanks for the hint

**Comment by reiniertc** [comment]
I'm going to close the issue, because I now stopped using this component
