### ISSUE TITLE
Remote Backup not copying backup file

### ISSUE THREAD

**Issue by yvansandoz** [carstenschroeder/hassio-addons#16]
After some HA OS updates (many of them on my Pi..) I realised that Remote Backup is not copying the full snapshot file via rsync to my Synology NAS as it did in the past. Single files from the Config folder are still being updated, telling me that my rsync connection should be ok. My automation did not change. Where should I look?

**Comment by carstenschroeder** [comment]
Did you have a look at the addon logs? My installation also went through lots of updates and backup and rsync still works.
Are the new backups not added to the remote folder?

**Comment by yvansandoz** [comment]
No backups added to the remote folder. Only files in the config folder are being updated.
Looking at the log, I have an issue, but I cannot locate it.

rsync: chgrp "/ha-backup/config/www/pictures/.logo_lfm.png.XSJrkD" (in NetBackup) failed: Operation not permitted (1)
rsync: chgrp "/ha-backup/config/www/pictures/.logo_pirates_radio.png.gbgCqi" (in NetBackup) failed: Operation not permitted (1)
rsync: chgrp "/ha-backup/config/www/pictures/.logo_radio_pilatus.png.7DJXwX" (in NetBackup) failed: Operation not permitted (1)
rsync: chgrp "/ha-backup/config/www/pictures/.logo_rougefm.png.qdkqDC" (in NetBackup) failed: Operation not permitted (1)
rsync: chgrp "/ha-backup/config/www/pictures/.logo_srf1.png.VBeZJh" (in NetBackup) failed: Operation not permitted (1)
rsync: chgrp "/ha-backup/config/www/pictures/.sia.jpg.sSgKQW" (in NetBackup) failed: Operation not permitted (1)
sent 6,578,462 bytes  received 4,245,664 bytes  195,029.30 bytes/sec
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=v20210212-7929-g0ba76c95]
total size is 90,338,701  speedup is 8.35
[cmd] /run.sh exited 23
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by carstenschroeder** [comment]
It seems that the rsync user does not have permissions to change group of the remote file. Do these source files belong to special groups?

**Comment by yvansandoz** [comment]
I will investigate. No quite sure where to start, but I will post an update if I find the root of the problem.

**Comment by yvansandoz** [comment]
Reading around from past similar issues, I am tempted to think it has to do with me running DSM 7.0 on my Synology. I am not sure how to solve that...
