### ISSUE TITLE
Error after starting add-on "Not:" command not found

### ISSUE THREAD

**Issue by ryanmboyce** [carstenschroeder/hassio-addons#2]
Thank you for forking this, it's a no brainer to get these backups of the SSD card. I installed the add-on however getting the following error when starting the docker container running hassio:

**/usr/bin/hassio: line 1: Not: command not found**

Is it possible that "Not:" is referenced somewhere because I have the command hassio installed in /usr/bin/hassio:
**a0d7b954-ssh:~/config# which hassio
/usr/bin/hassio**

Docker logs:
`Adding SSH key
Creating local backup: "Automated backup 2019-04-07 05:55"
/usr/bin/hassio: line 1: Not: command not found
Backup created: 
Copying .tar to /mnt/backupdir/ on **mybackup.remotehost.com** using SCP
Warning: Permanently added '[mybackup.remotehost.com]:22422,[172.16.0.100]:22422' (RSA) to the list of known hosts.
.tar: No such file or directory`

**Comment by carstenschroeder** [comment]
You might want to try new release 4.2.6. I had to upgrade to hassio-cli 2.2.0 in order to find a binary for the new armv7 arch. I guess you are running Hass.io on armv7?

After that I had to change some bash code, because hassio-cli Ver. 2 is not compatible to Ver. 1. 

It now seems to work in my installation (but I am on amd64). Please test yourself!

**Comment by ryanmboyce** [comment]
That is correct, I'm running Hass.io on armv7 on a RPI. When you are referring to the new release 4.2.6 what exact release are you referring to? Did you manually update your Hass.io instance hassio-cli binary?

**Comment by carstenschroeder** [comment]
The remote-backup-addon has a new release 4.2.6 in my repository. You should be able to update it in the hass.io dashboard. This release should be working also on armv7. The docker image now includes hassio-cli 2.2.0.
