### ISSUE TITLE
Doesn't want to ssh to Synology NAS after key setup

### ISSUE THREAD

**Issue by iDVB** [carstenschroeder/hassio-addons#5]
1. Added private key on HA addon
2. Uncommented `PubkeyAuthentication yes` and `AuthorizedKeysFile .ssh/authorized_keys`
3. Added public key on Synology to `.ssh/authorized_keys`
4. Rebooted ssh

```
Permission denied, please try again.
Permission denied, please try again.
homeassistant@192.168.1.100: Permission denied (publickey,password).
lost connection
```

```json
{
  "ssh_enabled": true,
  "ssh_host": "192.168.1.200",
  "ssh_port": 22,
  "ssh_user": "myuser",
  "ssh_key": [
    "-----BEGIN OPENSSH PRIVATE KEY-----",
    "...",
    "-----END OPENSSH PRIVATE KEY-----"
  ],
  "remote_directory": "ha_backup",
  "zip_password": "",
  "keep_local_backup": "",
  "rsync_enabled": false,
  "rsync_host": "192.168.1.200",
  "rsync_rootfolder": "ha_backup",
  "rsync_user": "myuser",
  "rsync_password": "mypass"
}
```

**Comment by Petro31** [comment]
I'm in the same position.  The only thing I can think of is that the documentation is poorly written.  I can log in using the host/user/ssh_key with putty but not this service.  Something else must be required.  It's also a really weird that the documentation calls out ---- ---- lines and requires a fragmented list for the ssh key.  I would expect this to work like every other add on, only require a single string.  BTW that doesn't appear to work either.

**Comment by Petro31** [comment]
Well I found the problem. If anyone stumbles upon this, the key that you need to use in the configuration needs to be formatted for openssh. If you're using puttykeygen... Conversions->Export OpenSSH Key (force new file format).
